version: '3'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom
      # - .:/app/node-dev
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_RELOAD_NODES_EVERY=10

volumes:
  n8n-data:
    name: n8n-data
